"""Fig 1A — Trial schematic (placeholder).

Trial diagram: 8 patients receive nivolumab + lenalidomide + low-dose dex
for 6 induction cycles, then 6 maintenance cycles of nivo+len. Paired BM
biopsies pre and post. Schematic is hand-drawn in Illustrator and not
generated by this pipeline. This script writes a placeholder PDF/SVG so
the figures/ directory has all expected panels.
"""
from __future__ import annotations
import matplotlib.pyplot as plt
import matplotlib as mpl
import _00_common as cm

mpl.rcParams.update({"font.family": "Arial", "font.size": 9,
                      "pdf.fonttype": 42, "svg.fonttype": "none"})

fig, ax = plt.subplots(figsize=(7, 1.2))
ax.text(0.5, 0.55,
         "Fig 1A — trial schematic (placeholder)",
         ha="center", va="center", fontsize=12, fontweight="bold",
         transform=ax.transAxes)
ax.text(0.5, 0.20,
         "Hand-drawn in Illustrator. Replace this PDF with the final asset.",
         ha="center", va="center", fontsize=9, style="italic", color="#555",
         transform=ax.transAxes)
ax.set_xticks([]); ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_color("#888")
    spine.set_linewidth(0.5)

cm.save_fig(fig, "Fig1A")
plt.close(fig)
print("wrote Fig1A (placeholder)")
