"""Supp Fig S1 — clinical figures (placeholder).

Swimmer plot, Kaplan-Meier curves, and CONSORT flow diagram are generated
by the clinical team using clinical CSVs that are not part of this
portable pipeline (they contain identifiable trial dates). Source scripts
are at `_archive/pipeline/3_clinical_figures/suppfig1{a,b,c,d,e}.py` and
require `_data.py` populated with clinical metadata. The CONSORT (panel
F) is hand-drawn in Illustrator from the trial flow.

This stub writes a placeholder so the figures/ directory has all six
expected panels.
"""
from __future__ import annotations
import matplotlib.pyplot as plt
import matplotlib as mpl
import _common as cm

mpl.rcParams.update({"font.family": "Arial", "font.size": 9,
                      "pdf.fonttype": 42, "svg.fonttype": "none"})

for tag, label in [
    ("SuppFigS1A", "Swimmer plot"),
    ("SuppFigS1B", "PFS by SLiM-CRAB"),
    ("SuppFigS1C", "Overall survival"),
    ("SuppFigS1D", "PFS by biochemical PD"),
    ("SuppFigS1E", "PFS by 2025 IMS/IMWG high-risk criteria"),
    ("SuppFigS1F", "CONSORT flow diagram"),
]:
    fig, ax = plt.subplots(figsize=(4.0, 2.5))
    ax.text(0.5, 0.55, f"{tag} — {label} (placeholder)",
             ha="center", va="center", fontsize=11, fontweight="bold",
             transform=ax.transAxes)
    ax.text(0.5, 0.25,
             "Generated by clinical team; see _archive/pipeline/3_clinical_figures/.",
             ha="center", va="center", fontsize=8,
             style="italic", color="#555", transform=ax.transAxes)
    ax.set_xticks([]); ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_color("#888")
        spine.set_linewidth(0.5)
    cm.save_fig(fig, tag)
    plt.close(fig)
print("wrote SuppFigS1A-F (placeholders)")
